name: Test

on: push

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
    steps:
      - uses: actions/checkout@v1
      - name: Install
        run: mvn install -B -DskipTests
      - name: Test
        run: mvn verify -B -DskipITs=false
